<a href="https://colab.research.google.com/github/Sagar-Puniyani/Python_Learn/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
L = [i for i in range(1000)]

In [3]:
L

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [4]:
n_arr = np.arange(1000)

In [5]:
n_arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [6]:
n_arr.itemsize # return size of every element

8

In [7]:
n_arr.size * n_arr.itemsize

8000

In [8]:
import sys

a = 10
print(sys.getsizeof(a))

28


In [9]:
import time

In [10]:
a = [i for i in range(1000000)]
b = [2*i for i in range(1000000)]

t1 = time.time()
c = [b[i] - a[i] for i in range(1000000)]
t2 = time.time()

t2 - t1


0.18136906623840332

In [11]:
n1 = np.arange(1000000)
n2 = np.arange(1000000)

t3 = time.time()
n3 = n2 - n1
t4 = time.time()

t4 - t3

0.0072021484375

In [12]:
l = [1 , 3 , 5 ,  6 ,  7 , 9.7 ]
np_array = np.array(l)

In [13]:
np_array

array([1. , 3. , 5. , 6. , 7. , 9.7])

In [14]:
n_type_array = np.array( l , dtype=np.int32)

In [15]:
n_type_array

array([1, 3, 5, 6, 7, 9], dtype=int32)

## 2D Array 👀👀👀

In [16]:
x = np.ones((3,2) , dtype=int)

In [17]:
x

array([[1, 1],
       [1, 1],
       [1, 1]])

In [18]:
a = np.full(4,7)

In [19]:
a

array([7, 7, 7, 7])

In [20]:
new_a = np.full((4,7) , 10)

In [21]:
new_a

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [22]:
x_linspace  = np.linspace(10 , 100 , 25 , endpoint=True )

In [23]:
x_linspace

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

### Slicing in Numpy array 🤞🤞✨✨✨

In [26]:
l = [ 10 , 20 , 30 , 40 , 50 ]
n_array = np.array(l , dtype='int32')

print(l[0:3])
print(n_array[0:3])

[10, 20, 30]
[10 20 30]


In [27]:
# pointer in Numpy array of first element
print(n_array.data)

In [28]:
# shape of  Numpy array
print(n_array.shape)

(5,)


In [29]:
# data trype of the numpy array
print(n_array.dtype)

int32


In [31]:
#  stride of Numpy array
print(n_array.strides)

(4,)


In [34]:
l1 = [ [1 , 2 , 3 , 4 , 5 ] , [6 , 7 , 8 , 9 , 10 ] , [11 , 12 , 13 , 14 , 15] ]
n_array1 =  np.array(l1 , dtype='int32')

print(l1)
print(n_array1)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [35]:
print(n_array1.strides)

(20, 4)


In [36]:
l1[0][0:6]

[1, 2, 3, 4, 5]

In [44]:
l1[0:3 ][0]

[1, 2, 3, 4, 5]

In [41]:
n_array1[0:2 , 3]

array([4, 9], dtype=int32)

In [46]:
n_array1[0:2 , 1:4]

array([[2, 3, 4],
       [7, 8, 9]], dtype=int32)

## Operations in Numpy 🧐🧐🧐🧐

In [49]:
l2 = [20 , 30 , 40 , 50 ]
l3 = [ 2*i for i in l2]

In [50]:
l3

[40, 60, 80, 100]

In [57]:
x = np.random.randint(10,40,10)

In [58]:
x

array([20, 35, 38, 38, 10, 36, 35, 38, 30, 33])

In [59]:
x = 2*x
print(x)

[40 70 76 76 20 72 70 76 60 66]


In [60]:
x = np.random.randint(10,40,10)
y = np.random.randint(10,40,10)

n1 = x + y
n2 = x - y
n3 = x * y
n4 = x / y

print(x)
print(y)
print(n1)
print(n2)
print(n3)
print(n4)

[26 22 22 38 39 25 13 16 36 17]
[23 10 33 21 19 15 15 29 20 31]
[49 32 55 59 58 40 28 45 56 48]
[  3  12 -11  17  20  10  -2 -13  16 -14]
[598 220 726 798 741 375 195 464 720 527]
[1.13043478 2.2        0.66666667 1.80952381 2.05263158 1.66666667
 0.86666667 0.55172414 1.8        0.5483871 ]


In [61]:
x = np.random.randint(10,50,8)
y = np.random.randint(10,50,8)

In [62]:
x

array([38, 25, 22, 13, 30, 26, 15, 38])

In [64]:
y

array([26, 30, 34, 41, 19, 24, 48, 39])

In [65]:
x>y

array([ True, False, False, False,  True,  True, False, False])

In [66]:
x==y

array([False, False, False, False, False, False, False, False])

In [67]:
x = np.array([1 , 7 , 0] , dtype='int32')
y = np.array([11 , 0 , 10] , dtype='int32')


In [68]:
x

array([1, 7, 0], dtype=int32)

In [69]:
y

array([11,  0, 10], dtype=int32)

In [71]:
np.logical_or(x,y)

array([ True,  True,  True])

In [72]:
np.logical_and(x,y)

array([ True, False, False])

In [73]:
def step(z)->bool:
  if (z>0):
    return 1
  else:
    return 0

In [74]:
step(8.0)

1

In [75]:
step(-89)

0

In [76]:
y = np.random.randint(10,50,10 , dtype='int32')

In [77]:
y

array([22, 37, 15, 35, 45, 24, 16, 12, 38, 27], dtype=int32)

In [78]:
boolean_arr = y>25

In [79]:
boolean_arr

array([False,  True, False,  True,  True, False, False, False,  True,
        True])

In [80]:
arr1 = y[boolean_arr]

In [81]:
arr1

array([37, 35, 45, 38, 27], dtype=int32)